language: php

matrix:
  include:
    - php: 7
      env: DB=sqlite
    - php: 7
      env: DB=mysql

sudo: false

install:
  - travis_retry composer install
  - npm install

before_script:
  - phpenv config-rm xdebug.ini
  - bash build/travis/installKontoCheck.sh
  - if [ "$DB" == "mysql" ]; then bash build/travis/configureForMysql.sh; fi

script: composer ci

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

notifications:
  email:
    on_success: change
    on_failure: always