- name: Checkout code
  git: repo=https://github.com/wmde/FundraisingFrontend.git dest={{ build_dir }} version={{ build_branch }}

- name: Install PHP dependencies
  composer: command=install working_dir={{ build_dir }} no_dev={{ composer_no_dev }} optimize_autoloader=yes

- name: Install JavaScript dependencies
  npm: path={{ build_dir }}

- name: Compile JavaScript
  command: npm run build-js chdir={{ build_dir }}

- name: Create tarball
  shell: tar -czf {{ build_dir }}.tar.gz --exclude=".git" --exclude=node_modules -C {{ build_dir }} . warn=no